2024-02-06 14:32:18,100 - ERROR - Exception: 'data'
2024-02-07 08:58:08,243 - ERROR - HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /vending_status/?ip_address=192.168.1.4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002F009614A70>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
2024-02-07 14:34:58,518 - ERROR - Error processing takeout request: HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /checkout/?user_id=1234567891&product_id=87 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020FD0F9EF30>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
2024-02-07 14:53:01,750 - ERROR - Exception: HTTPConnectionPool(host='192.168.1.4', port=8000): Max retries exceeded with url: /check_user/?user_id=1234567891&ip_address=192.168.1.4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020FD0F45160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-02-07 14:53:38,492 - ERROR - Error processing takeout request: HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /checkout/?user_id=1234567891&product_id=87 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020FD0FF2300>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
2024-02-07 14:53:54,316 - ERROR - Error processing takeout request: HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /checkout/?user_id=1234567891&product_id=90 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020FD0FCA2A0>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
2024-02-08 10:17:07,310 - ERROR - Exception: 'data'
2024-02-08 10:18:26,660 - ERROR - Exception: 'data'
2024-02-08 10:18:35,189 - ERROR - Exception: 'data'
2024-02-08 10:18:52,877 - ERROR - Exception: 'data'
2024-02-08 10:19:17,168 - ERROR - Exception: 'data'
2024-02-08 10:19:31,869 - ERROR - Exception: 'data'
2024-02-08 10:20:24,557 - ERROR - Exception: 'data'
2024-02-08 10:20:50,249 - ERROR - Exception: 'data'
2024-02-08 10:20:57,060 - ERROR - Exception: 'data'
2024-02-08 10:21:07,773 - ERROR - Exception: 'data'
2024-02-08 10:26:27,064 - ERROR - Exception: 'data'
2024-02-08 10:26:34,477 - ERROR - Exception: 'data'
2024-02-08 10:26:50,309 - ERROR - Exception: 'data'
2024-02-08 10:26:54,282 - ERROR - Exception: 'data'
2024-02-08 10:27:01,507 - ERROR - Exception: 'data'
2024-02-08 10:27:06,556 - ERROR - Exception: 'data'
2024-02-08 10:27:19,125 - ERROR - Exception: 'data'
2024-02-08 10:27:26,444 - ERROR - Exception: 'data'
2024-02-08 10:27:34,878 - ERROR - Exception: 'data'
2024-02-08 10:27:40,806 - ERROR - Exception: 'data'
2024-02-08 10:27:46,601 - ERROR - Exception: 'data'
2024-02-08 10:27:56,274 - ERROR - Exception: 'data'
2024-02-08 10:28:08,810 - ERROR - Exception: 'data'
2024-02-08 10:28:34,611 - ERROR - Exception: 'data'
2024-02-08 10:28:40,113 - ERROR - Exception: 'data'
2024-02-08 10:28:52,135 - ERROR - Exception: 'data'
2024-02-08 10:29:00,707 - ERROR - Exception: 'data'
2024-02-08 10:29:10,555 - ERROR - Exception: 'data'
2024-02-08 10:29:55,316 - ERROR - Exception: 'data'
2024-02-08 10:30:22,998 - ERROR - Exception: 'data'
2024-02-08 10:31:18,029 - ERROR - Exception: 'data'
2024-02-08 10:32:45,739 - ERROR - Exception: 'data'
2024-02-08 10:34:25,528 - ERROR - Exception: 'data'
2024-02-08 10:36:02,820 - ERROR - Exception: 'data'
2024-02-08 10:36:27,106 - ERROR - Exception: 'data'
2024-02-08 10:36:39,931 - ERROR - Exception: 'data'
2024-02-08 10:36:51,152 - ERROR - Exception: 'data'
2024-02-08 10:37:13,837 - ERROR - Exception: 'data'
2024-02-08 10:37:21,115 - ERROR - Exception: 'data'
2024-02-08 10:37:26,562 - ERROR - Exception: 'data'
2024-02-08 10:37:33,954 - ERROR - Exception: 'data'
2024-02-08 10:38:30,194 - ERROR - Exception: 'data'
2024-02-08 10:39:02,328 - ERROR - Exception: 'data'
2024-02-08 10:39:17,394 - ERROR - Exception: 'data'
2024-02-08 10:39:22,536 - ERROR - Exception: 'data'
2024-02-08 10:39:43,808 - ERROR - Exception: 'data'
2024-02-08 10:41:02,269 - ERROR - Exception: 'data'
2024-02-08 10:41:44,043 - ERROR - Exception: 'data'
2024-02-08 10:42:05,566 - ERROR - Exception: 'data'
2024-02-08 10:42:22,130 - ERROR - Exception: 'data'
2024-02-08 10:42:45,507 - ERROR - Exception: 'data'
2024-02-08 10:43:19,247 - ERROR - Exception: 'data'
2024-02-08 10:48:01,063 - ERROR - Exception: 'data'
2024-02-08 12:08:37,050 - ERROR - 'data' is undefined
2024-02-08 12:11:10,963 - ERROR - 'data' is undefined
2024-02-08 12:13:24,415 - ERROR - 'data' is undefined
2024-02-08 12:17:24,605 - ERROR - Error processing takeout request: 'image_url' is undefined
2024-02-08 12:49:58,642 - ERROR - Error processing takeout request: 'fio' is undefined
2024-02-08 12:50:30,202 - ERROR - Error processing takeout request: 'fio' is undefined
2024-02-08 13:05:13,899 - ERROR - Error processing takeout request: 'fio' is undefined
2024-02-08 15:09:20,027 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-08 15:09:43,902 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-08 15:10:15,817 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-08 15:11:19,725 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-08 15:12:30,105 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-08 15:12:49,759 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-08 15:13:18,602 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-08 15:14:09,052 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-09 11:46:59,840 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-09 11:47:21,512 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-09 11:48:11,410 - ERROR - Error processing takeout request: invalid syntax (<unknown>, line 1)
2024-02-09 11:49:07,378 - ERROR - Exception: 'data'
2024-02-27 09:32:13,360 - ERROR - Error processing takeout request: HTTPConnectionPool(host='192.168.9.94', port=8000): Max retries exceeded with url: /get_goods/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001756A02D9D0>, 'Connection to 192.168.9.94 timed out. (connect timeout=None)'))
